### ISSUE TITLE
Error after updating the module

### ISSUE THREAD

**Issue by gdelfava** [Payfast/mod-whmcs#12]
I get this error after updating module after accessing the Payment Gateways menu item

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the [WHMCS TroubleShooting Guide »](https://docs.whmcs.com/Troubleshooting_Guide)

ParseError: syntax error, unexpected '|', expecting '{' in public_html/clientportal/modules/gateways/payfast.php:157
Stack trace:
public_html/clientportal/admin/configgateways.php(0): WHMCS\Module\Gateway->load('payfast')
#1 {main}

**Comment by shabsta** [comment]
You should remove the path to your domain

**Comment by gdelfava** [comment]
How do I do that. Please in detail.

**Comment by shabsta** [comment]
in your detail of the issue, remove and redact information relating to the structure of your site ;)

**Comment by jaysonwebtel** [comment]
Make sure your WHMCS is updated to a recent version and that you are running it on PHP 8.1. 
Also there have been a number of changes to the file structure for this plugin over the last few releases so its best to make sure you remove all the old files and then upload only the new ones - dont try to replace the folder   That worked for me. Havent had issued with the current versions.

**Comment by shabsta** [comment]
I too received the "upgrade module" email and thought I would wait till there are dedicated resources available to assist.

Cannot afford to have payments down

**Comment by gdelfava** [comment]
Upgrading to PHP 8.1 Fixed the issue for me.

**Comment by jaysonwebtel** [comment]
If you look back at the release notes you will see version 2.2.3 was updated to PHP 8. (but ioncube doesnt support PHP 8 - only PHP8.1 and newer. ).
