### ISSUE TITLE
TypeError: fwrite(): supplied resource is not a valid stream resource in /home/user/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php

### ISSUE THREAD

**Issue by biovolt** [Payfast/mod-whmcs#15]
Morning 
The issue from https://github.com/Payfast/mod-whmcs/issues/9 is still there.

It was just wrapped in a try-catch so the error still happens almost every day

This is the new code just wrapping the fwrite.
 `                    try {
                        fwrite($fh, $line);
                    } catch (\Exception $e) {
                        error_log($e, 0);
                    }`

Please see why it happens

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Oops!</title>
    
<style>
        body {
            margin: 30px 40px;
            background-color: #f6f6f6;
        }
        .error-container {
            padding: 50px 40px;
            font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
            font-size: 14px;
        }
        h1 {
            margin: 0;
            font-size: 48px;
            font-weight: 400;
        }
        h2 {
            margin: 0;
            font-size: 26px;
            font-weight: 300;
        }
        a {
            color: #336699;
        }
        p.back-to-home {
            margin-top: 30px;
        }
        p.debug{
            padding: 20px 0;
            font-family: "Courier New", Courier, monospace, serif;
            font-size: 14px;
        }
        .info {
            border: solid 1px #999;
            padding: 5px;
            background-color: #d9edf7;
        }
    </style>

  </head>
  <body>
    <div class="error-container">
<h1>Oops!</h1>
<h2>Something went wrong and we couldn't process your request.</h2>
<p>Please go back to the previous page and try again.</p>
<p class="debug"><br/>TypeError: fwrite(): supplied resource is not a valid stream resource in /home/whmcs/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php:179<br />
Stack trace:<br />
#0 /home/whmcs/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php(179): fwrite(Resource id #965, '2023-10-31 08:0...')<br />
#1 /home/whmcs/modules/gateways/payfast.php(350): Payfast\PayfastCommon\PayfastCommon::pflog('Payfast capture...')<br />
#2 [internal function]: Payfast_capture(Array)<br />
#3 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('payfast_capture', Array)<br />
#4 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): WHMCS\Module\AbstractModule->call('capture', Array)<br />
#5 /home/whmcs/includes/ccfunctions.php(0): WHMCS\Module\Gateway->call('capture', Array)<br />
#6 /home/whmcs/includes/ccfunctions.php(0): captureCCPayment(59021)<br />
#7 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Cron/Task/ProcessCreditCardPayments.php(0): ccProcessing(Object(WHMCS\Cron\Task\ProcessCreditCardPayments))<br />
#8 [internal function]: WHMCS\Cron\Task\ProcessCreditCardPayments->__invoke()<br />
#9 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): call_user_func_array(Object(WHMCS\Cron\Task\ProcessCreditCardPayments), Array)<br />
#10 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute()<br />
#11 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run()<br />
#12 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection))<br />
#13 /home/whmcs/vendor/symfony/console/Command/Command.php(298): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))<br />
#14 /home/whmcs/vendor/symfony/console/Application.php(1028): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))<br />
#15 /home/whmcs/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))<br />
#16 /home/whmcs/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))<br />
#17 /home/whmcs/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))<br />
#18 {main}</p></div>
  </body>
</html>`

**Comment by appinlet** [comment]
@biovolt thank you for logging this issue.

In order to further expedite the issue, please kindly confirm your ticket number (if you do not have one, please kindly submit a ticket at https://support.payfast.help/portal/en/kb/).
