### ISSUE TITLE
tried the september version with whmcs gives errors

### ISSUE THREAD

**Issue by azizarnold** [Payfast/mod-whmcs#18]
[WHMCS Application] ERROR: TypeError: fwrite(): supplied resource is not a valid stream resource in /home/my/domains/my.domainname.com/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php:185 Stack trace: #0 /home/my/domains/my.domainname.com/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php(185): fwrite() #1 /home/my/domains/my.domainname.com/public_html/modules/gateways/payfast.php(357): Payfast\PayfastCommon\PayfastCommon->pflog() #2 [internal function]: Payfast_capture() #3 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func() #4 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): WHMCS\Module\AbstractModule->call() #5 /home/my/domains/my.domainname.com/public_html/includes/ccfunctions.php(0): WHMCS\Module\Gateway->call() #6 /home/my/domains/my.domainname.com/public_html/includes/ccfunctions.php(0): captureCCPayment() #7 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Task/ProcessCreditCardPayments.php(0): ccProcessing() #8 [internal function]: WHMCS\Cron\Task\ProcessCreditCardPayments->__invoke() #9 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): call_user_func_array() #10 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute() #11 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run() #12 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection() #13 /home/my/domains/my.domainname.com/public_html/vendor/symfony/console/Command/Command.php(298): WHMCS\Cron\Console\Command\AbstractCronCommand->execute() #14 /home/my/domains/my.domainname.com/public_html/vendor/symfony/console/Application.php(1028): Symfony\Component\Console\Command\Command->run() #15 /home/my/domains/my.domainname.com/public_html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand() #16 /home/my/domains/my.domainname.com/public_html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun() #17 /home/my/domains/my.domainname.com/crons/cron.php(0): Symfony\Component\Console\Application->run() #18 {main} {"exception":"[object] (TypeError(code: 0): fwrite(): supplied resource is not a valid stream resource at /home/my/domains/my.domainname.com/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php:185)"} []
TypeError: fwrite(): supplied resource is not a valid stream resource in /home/my/domains/my.domainname.com/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php:185

#0 /home/my/domains/my.domainname.com/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php(185): fwrite()
#1 /home/my/domains/my.domainname.com/public_html/modules/gateways/payfast.php(357): Payfast\PayfastCommon\PayfastCommon->pflog()
#2 [internal function]: Payfast_capture()
#3 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func()
#4 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): WHMCS\Module\AbstractModule->call()
#5 /home/my/domains/my.domainname.com/public_html/includes/ccfunctions.php(0): WHMCS\Module\Gateway->call()
#6 /home/my/domains/my.domainname.com/public_html/includes/ccfunctions.php(0): captureCCPayment()
#7 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Task/ProcessCreditCardPayments.php(0): ccProcessing()
#8 [internal function]: WHMCS\Cron\Task\ProcessCreditCardPayments->__invoke()
#9 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): call_user_func_array()
#10 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute()
#11 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run()
#12 /home/my/domains/my.domainname.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection()
#13 /home/my/domains/my.domainname.com/public_html/vendor/symfony/console/Command/Command.php(298): WHMCS\Cron\Console\Command\AbstractCronCommand->execute()
#14 /home/my/domains/my.domainname.com/public_html/vendor/symfony/console/Application.php(1028): Symfony\Component\Console\Command\Command->run()
#15 /home/my/domains/my.domainname.com/public_html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#16 /home/my/domains/my.domainname.com/public_html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#17 /home/my/domains/my.domainname.com/crons/cron.php(0): Symfony\Component\Console\Application->run()

**Comment by appinlet** [comment]
@azizarnold this issue was targeted in https://github.com/Payfast/mod-whmcs/releases/tag/v2.3.0.

Should you still be experiencing an issue after updating, please feel free to [contact the Payfast support team](https://payfast.io/contact/) for further assistance.
