### ISSUE TITLE
Invoices no longer get marked as paid

### ISSUE THREAD

**Issue by hyperlayersa** [PayFast/mod-whmcs#2]
On this latest version when an invoice gets paid it doesn't get market as paid on whmcs. 

We need to manually add the payment.

Also recurring billing doesn't seem to place in the subscription id in the product/service but it gets listed in payfasts ad-hoc agreements.

Not sure if this is related but on checkout payment forces you to sign into payfast it used to ask you to choose your payment method in payfast for example credit card, instant EFT etc etc.

**Comment by shabsta** [comment]
We've seen two invoices which have received payment but have not been marked as paid.

This from Payfast regarding subscription services
"Essentially we are storing the ad hoc token from PayFast in the credit card field on the client's record. As Admin, you can check the under "Client Information", click "Credit Card Information" and you will see the token in "Remote Gateway Token". 

When you have "Enable Recurring Billing", and the client checks out without a token, they will need to sign up for a token. The token can then be used in future if a cron is set up for them.
When the client checks out and has a token already, they will be shown all the payment methods that you have enabled on your PayFast account and pay anyway they would like to. 

I hope that clears things up. If you have any further questions, please let me know. "

**Comment by hyperlayersa** [comment]
HI There,

Thanks i have found the ID in Credit Card Information.

ok Token signup makes sense. Thanks for Clearing

We are not using the default six theme in whmcs and since this modules latest update the buttons look like they have swapped Make payment takes you to subscribe and subscribe takes you to make payment. Any idea how to fix it? 

I have attached images of the payfast pay buttons and how it should look like using paypal method 
![6312ce154aca77d400193748cd03d8f3](https://user-images.githubusercontent.com/51609981/62689146-89ec2e00-b9ca-11e9-9175-972a0f511dd6.png)
![a7759e1b71e26f695e7f147ea58d185f](https://user-images.githubusercontent.com/51609981/62689209-ab4d1a00-b9ca-11e9-8351-1d55dbdd23ef.png)

**Comment by RheinhardtSnyman** [comment]
@hyperlayersa The module generates HTML output which is returned to built in WHMCS functionality that displays it on the invoice. The PayFast module has been tested for WHMCS default theme only. 

You can try specifying only one payment button by enabling Force Recurring Billing.
Alternatively you may need to customize your code for compatibility with how your theme renders the HTML buttons.

Please follow up on support@payfast.co.za for further assistance.

**Comment by hyperlayersa** [comment]
Im re-opening this because i dont know what to do anymore and payfast support do not help in anyway 

They just tell me to send the log file but mine is empty with full 777 permissions...

After getting client payments since my last post ive done some testing

We at the beginning of the month enabled UFW  and locked down all our servers entirely only allowing ports 80 443 and 22 via VPN

Ive added all all payfasts subnets and ports into ufw aswell for the API.

upon testing it seems invoices get marked as paid if the clients invoice is recurring

New orders dont seem to get marked as paid at all

I have now turned off ufw completely lets see what happens.
