### ISSUE TITLE
Incorrect transaction ID

### ISSUE THREAD

**Issue by jaysonwebtel** [PayFast/mod-whmcs#3]
Previously the Module used to post pf_payment_id to the transid field which indicated the Payfast transaction ID in WHMCS, but now you are posting m_payment_id instead, which is the invoice number so it is confusing as the invoice number is already being received and we need to see the transaction ID for accounting purposes.

See example of previous and current Transcations below. 
![image](https://user-images.githubusercontent.com/29201035/63079773-9b3fb800-bf3f-11e9-9a2d-48fa3b631eeb.png)

**Comment by shabsta** [comment]
Concur that we have the same issue

**Comment by RheinhardtSnyman** [comment]
Currently, the Transaction ID is set to the Merchant's payment ID(m_payment_id) which is meant to be a unique payment ID on the merchant’s system.
Is there a reason the PayFast Transaction ID(pf_payment_id) is preferred for accounting rather than the Invoice ID?

**Comment by jaysonwebtel** [comment]
Its helps with doing a recon with Payfast transaction History, with Auditing and with Queries as it saves us having to login to your site to see the transaction ID.

**Comment by shabsta** [comment]
Any update on this?

**Comment by RheinhardtSnyman** [comment]
We are currently looking into the best way to set the transaction ID to the pf_payment_id, which will be added in a future update.
For more information please contact support@payfast.co.za, we will also close this issue once changes have been made.

**Comment by RheinhardtSnyman** [comment]
The transaction ID is now set to the pf_payment_id.
